### ISSUE TITLE
[Bug] after update on tcadmin

### ISSUE THREAD

**Issue by laggis** [M0RG4N01/TCAdminMySqlModule#6]
So i installed the new version of tcadmin to 2.0.158.0 and that make mysql manger to break so ppl cant see there info about the databas and it even deleted some database
![image_2020-09-30_180020](https://user-images.githubusercontent.com/18127838/94710160-ce612880-0346-11eb-965c-0e67c58cf714.png)

**Comment by M0RG4N01** [comment]
This is likely resulted due to the latest TCAdmin version using an update of Kendo, and since the plugin was built with TCAdmin 2.0.157, it won't have this kendo update so its probably why the items are not showing in the grid. But the databases definitely shouldn't be deleted and will still exist in the TCAdmin database, as on the right of the screenshot it gets one of the created database(s) if you look at the dropdown 👍 

But I will be releasing a module update soon with some new features which will be built with the latest TCAdmin version including the new kendo update :)

**Comment by M0RG4N01** [comment]
Module has been updated for 2.0.158.0
